// Dummy data — all passwords are "demo"

const USERS = [
  {
    id: 1,
    name: "Alex Rivera",
    email: "alex@demo.com",
    password: "demo",
    phone: "555-0101",
    elo: 1850,
    role: "admin",
    createdAt: "2024-01-15",
    eloHistory: [
      { label: "Jan", elo: 1500 },
      { label: "Feb", elo: 1560 },
      { label: "Mar", elo: 1640 },
      { label: "Apr", elo: 1600 },
      { label: "May", elo: 1700 },
      { label: "Jun", elo: 1760 },
      { label: "Jul", elo: 1820 },
      { label: "Aug", elo: 1850 },
    ],
  },
  {
    id: 2,
    name: "Jordan Park",
    email: "jordan@demo.com",
    password: "demo",
    phone: "555-0102",
    elo: 1720,
    role: "user",
    createdAt: "2024-02-20",
    eloHistory: [
      { label: "Jan", elo: 1500 },
      { label: "Feb", elo: 1530 },
      { label: "Mar", elo: 1510 },
      { label: "Apr", elo: 1580 },
      { label: "May", elo: 1620 },
      { label: "Jun", elo: 1650 },
      { label: "Jul", elo: 1700 },
      { label: "Aug", elo: 1720 },
    ],
  },
  {
    id: 3,
    name: "Casey Kim",
    email: "casey@demo.com",
    password: "demo",
    phone: "555-0103",
    elo: 1680,
    role: "user",
    createdAt: "2024-03-05",
    eloHistory: [
      { label: "Jan", elo: 1500 },
      { label: "Feb", elo: 1480 },
      { label: "Mar", elo: 1540 },
      { label: "Apr", elo: 1600 },
      { label: "May", elo: 1620 },
      { label: "Jun", elo: 1680 },
    ],
  },
  {
    id: 4,
    name: "Morgan Lee",
    email: "morgan@demo.com",
    password: "demo",
    phone: "555-0104",
    elo: 1645,
    role: "user",
    createdAt: "2024-03-15",
    eloHistory: [
      { label: "Mar", elo: 1500 },
      { label: "Apr", elo: 1520 },
      { label: "May", elo: 1560 },
      { label: "Jun", elo: 1600 },
      { label: "Jul", elo: 1645 },
    ],
  },
  {
    id: 5,
    name: "Riley Chen",
    email: "riley@demo.com",
    password: "demo",
    phone: "555-0105",
    elo: 1610,
    role: "user",
    createdAt: "2024-04-10",
    eloHistory: [
      { label: "Apr", elo: 1500 },
      { label: "May", elo: 1530 },
      { label: "Jun", elo: 1570 },
      { label: "Jul", elo: 1610 },
    ],
  },
  {
    id: 6,
    name: "Sam Torres",
    email: "sam@demo.com",
    password: "demo",
    phone: "555-0106",
    elo: 1590,
    role: "user",
    createdAt: "2024-04-20",
    eloHistory: [
      { label: "Apr", elo: 1500 },
      { label: "May", elo: 1490 },
      { label: "Jun", elo: 1540 },
      { label: "Jul", elo: 1590 },
    ],
  },
  {
    id: 7,
    name: "Drew Patel",
    email: "drew@demo.com",
    password: "demo",
    phone: "555-0107",
    elo: 1565,
    role: "user",
    createdAt: "2024-05-01",
    eloHistory: [
      { label: "May", elo: 1500 },
      { label: "Jun", elo: 1520 },
      { label: "Jul", elo: 1565 },
    ],
  },
  {
    id: 8,
    name: "Quinn Foster",
    email: "quinn@demo.com",
    password: "demo",
    phone: "555-0108",
    elo: 1540,
    role: "user",
    createdAt: "2024-05-15",
    eloHistory: [
      { label: "May", elo: 1500 },
      { label: "Jun", elo: 1510 },
      { label: "Jul", elo: 1540 },
    ],
  },
];

const GAMES = [
  {
    id: 1,
    name: "Monday Night Showdown",
    description:
      "Weekly competitive rotational game. Players challenge the reigning King to earn their throne. All skill levels welcome!",
    status: "planned",
    plannedAt: "2026-05-12T19:00",
    location: "Court A",
    maxParticipants: 8,
    participants: [
      { userId: 2, name: "Jordan Park", elo: 1720 },
      { userId: 3, name: "Casey Kim", elo: 1680 },
      { userId: 5, name: "Riley Chen", elo: 1610 },
    ],
  },
  {
    id: 2,
    name: "Weekend Warriors Cup",
    description:
      "Casual weekend tournament with rotating partners. Great for building skills and meeting new players.",
    status: "planned",
    plannedAt: "2026-05-14T10:00",
    location: "Court B",
    maxParticipants: 6,
    participants: [
      { userId: 1, name: "Alex Rivera", elo: 1850 },
      { userId: 4, name: "Morgan Lee", elo: 1645 },
    ],
  },
  {
    id: 3,
    name: "Thursday Rapid Round",
    description: "Fast-paced format. 10-minute rounds, winner stays on.",
    status: "planned",
    plannedAt: "2026-05-16T18:30",
    location: "Court A",
    maxParticipants: 10,
    participants: [
      { userId: 6, name: "Sam Torres", elo: 1590 },
      { userId: 7, name: "Drew Patel", elo: 1565 },
      { userId: 8, name: "Quinn Foster", elo: 1540 },
    ],
  },
  {
    id: 4,
    name: "Spring League Finals",
    description:
      "Season finale. Top players from the spring league compete for the championship.",
    status: "started",
    plannedAt: "2026-05-07T15:00",
    location: "Main Court",
    maxParticipants: 6,
    participants: [
      { userId: 1, name: "Alex Rivera", elo: 1850 },
      { userId: 2, name: "Jordan Park", elo: 1720 },
      { userId: 3, name: "Casey Kim", elo: 1680 },
      { userId: 4, name: "Morgan Lee", elo: 1645 },
      { userId: 5, name: "Riley Chen", elo: 1610 },
      { userId: 6, name: "Sam Torres", elo: 1590 },
    ],
  },
  {
    id: 5,
    name: "April Open",
    description: "Monthly open tournament.",
    status: "ended",
    plannedAt: "2026-04-20T14:00",
    endedAt: "2026-04-20T17:00",
    location: "Court A",
    maxParticipants: 8,
    participants: [
      { userId: 1, name: "Alex Rivera", elo: 1830 },
      { userId: 2, name: "Jordan Park", elo: 1700 },
      { userId: 3, name: "Casey Kim", elo: 1650 },
      { userId: 5, name: "Riley Chen", elo: 1580 },
    ],
    winnerUserId: 1,
    winnerName: "Alex Rivera",
  },
  {
    id: 6,
    name: "Midweek Mixer",
    description: "Casual midweek game for all levels.",
    status: "ended",
    plannedAt: "2026-04-08T19:00",
    endedAt: "2026-04-08T21:00",
    location: "Court B",
    maxParticipants: 8,
    participants: [
      { userId: 2, name: "Jordan Park", elo: 1680 },
      { userId: 4, name: "Morgan Lee", elo: 1620 },
      { userId: 6, name: "Sam Torres", elo: 1560 },
      { userId: 7, name: "Drew Patel", elo: 1530 },
    ],
    winnerUserId: 2,
    winnerName: "Jordan Park",
  },
  {
    id: 7,
    name: "March Madness Royale",
    description: "End of month tournament.",
    status: "ended",
    plannedAt: "2026-03-28T15:00",
    endedAt: "2026-03-28T18:30",
    location: "Main Court",
    maxParticipants: 8,
    participants: [
      { userId: 1, name: "Alex Rivera", elo: 1800 },
      { userId: 2, name: "Jordan Park", elo: 1660 },
      { userId: 3, name: "Casey Kim", elo: 1600 },
      { userId: 4, name: "Morgan Lee", elo: 1560 },
      { userId: 5, name: "Riley Chen", elo: 1530 },
      { userId: 8, name: "Quinn Foster", elo: 1500 },
    ],
    winnerUserId: 3,
    winnerName: "Casey Kim",
  },
];
